version: "3"
services:
    docker-mysql-tutorial:
        image: mysql:latest
        container_name: c-mysql
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=admin25112002